#! /usr/bin/env bash
# https://medium.com/zumba-tech/enforce-code-standards-with-composer-git-hooks-and-phpcs-3a1c088550a5

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
  oIFS=$IFS
  IFS='
  '
  SFILES="$1"
  IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}
echo "Checking PHP Lint..."
for FILE in $SFILES
do
  php -l -d display_errors=0 $PROJECT/$FILE
  if [ $? != 0 ]
  then
    echo "Fix the error before commit."
    exit 1
  fi
  FILES="$FILES $PROJECT/$FILE"
done
echo "...Finished Checking PHP Lint"
if [ "$FILES" != "" ]
then
  echo "Running PHP CS FIXER..."
  ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=tools/php-cs-fixer/.php-cs-fixer.php -vvv --show-progress=dots $FILES
  if [ $? != 0 ]
  then
    echo "Fix the error before commit."
    exit 1
  fi
  echo "...Finished Running PHP CS FIXER"
fi

exit $?
